name: diu_evento
description: "A new Flutter project."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  # The following section is specific to Flutter packages.

  firebase_core:
  firebase_auth:
  firebase_auth_web:
  cloud_firestore:
  firebase_storage:
  fl_chart:
  google_sign_in:

  cupertino_icons: ^1.0.8

  # The following adds the Cupertino Icons font to your application.

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
