// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-OkeO8xseKGy4Z62zSKXyTc4UYmGewYs',
    appId: '1:336469512031:web:bec98691ff6bec5d7db0ea',
    messagingSenderId: '336469512031',
    projectId: 'diu-event-managemtn',
    authDomain: 'diu-event-managemtn.firebaseapp.com',
    storageBucket: 'diu-event-managemtn.firebasestorage.app',
    measurementId: 'G-7ESGN3KDBP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKWjazqf3_GJ1MrNJvcd_g2B9RVe4F5-8',
    appId: '1:336469512031:android:aad0bfb0bfcfb9c37db0ea',
    messagingSenderId: '336469512031',
    projectId: 'diu-event-managemtn',
    storageBucket: 'diu-event-managemtn.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD20Ue2VIETXzfYl7lNhTVnqgRoWVGncy4',
    appId: '1:336469512031:ios:da256c92554c93077db0ea',
    messagingSenderId: '336469512031',
    projectId: 'diu-event-managemtn',
    storageBucket: 'diu-event-managemtn.firebasestorage.app',
    iosBundleId: 'com.example.diuEvento',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD20Ue2VIETXzfYl7lNhTVnqgRoWVGncy4',
    appId: '1:336469512031:ios:da256c92554c93077db0ea',
    messagingSenderId: '336469512031',
    projectId: 'diu-event-managemtn',
    storageBucket: 'diu-event-managemtn.firebasestorage.app',
    iosBundleId: 'com.example.diuEvento',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-OkeO8xseKGy4Z62zSKXyTc4UYmGewYs',
    appId: '1:336469512031:web:b29a0bb16f80f5267db0ea',
    messagingSenderId: '336469512031',
    projectId: 'diu-event-managemtn',
    authDomain: 'diu-event-managemtn.firebaseapp.com',
    storageBucket: 'diu-event-managemtn.firebasestorage.app',
    measurementId: 'G-3X6L7SF05F',
  );
}
